#!/bin/sh
#    Copyright 2022 Red Hat, Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

lint_args="--check"

usage() {
    echo "Usage: $0 [-r | --reformat]"
}

PARSED_ARGS=$(getopt -a -n lint -o r --long reformat -- "$@")
if [ "$?" != "0" ]
then
    exec 1>&2
    usage
    exit 2
fi

eval set -- "$PARSED_ARGS"
while :
do
    case $1 in
        -r | --reformat) lint_args=""; shift ;;
        --) shift; break;;
    esac
done

black $lint_args .
