#!/bin/sh

lint_args="--check"

usage() {
    echo "Usage: $0 [-r | --reformat]"
}

PARSED_ARGS=$(getopt -a -n lint -o r --long reformat -- "$@")
if [ "$?" != "0" ]
then
    exec 1>&2
    usage
    exit 2
fi

eval set -- "$PARSED_ARGS"
while :
do
    case $1 in
        -r | --reformat) lint_args=""; shift ;;
        --) shift; break;;
    esac
done

black $lint_args .
